var searchData=
[
  ['s_3a_20strong_0',['&lt;strong&gt;Do&apos;s:&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md54',1,'']]],
  ['saved_20automatically_3a_20strong_1',['&lt;strong&gt;What Gets Saved Automatically:&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md34',1,'']]],
  ['settings_2',['settings',['../md_CONFIG__README.html#autotoc_md16',1,'&lt;strong&gt;HardwareConfig&lt;/strong&gt; - Device Settings'],['../md_CONFIG__README.html#autotoc_md15',1,'&lt;strong&gt;WiFiConfig&lt;/strong&gt; - Network Settings'],['../md_README.html#autotoc_md69',1,'MQTT Settings'],['../md_README.html#autotoc_md68',1,'WiFi Settings']]],
  ['setup_20strong_3',['&lt;strong&gt;Initialization (in setup())&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md22',1,'']]],
  ['singleton_20strong_4',['&lt;strong&gt;3. Main Config Class (Singleton)&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md4',1,'']]],
  ['software_20dependencies_5',['Software Dependencies',['../md_README.html#autotoc_md64',1,'']]],
  ['status_20debugging_6',['📊 Configuration Status &amp; Debugging',['../md_CONFIG__README.html#autotoc_md47',1,'']]],
  ['step_201_3a_20add_20constants_20if_20needed_20strong_7',['&lt;strong&gt;Step 1: Add Constants (if needed)&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md43',1,'']]],
  ['step_202_3a_20create_20runtime_20config_20class_20strong_8',['&lt;strong&gt;Step 2: Create Runtime Config Class&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md44',1,'']]],
  ['step_203_3a_20add_20to_20main_20config_20class_20strong_9',['&lt;strong&gt;Step 3: Add to Main Config Class&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md45',1,'']]],
  ['storage_10',['💾 Persistence &amp; Storage',['../md_CONFIG__README.html#autotoc_md33',1,'']]],
  ['storage_20details_3a_20strong_11',['&lt;strong&gt;Storage Details:&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md35',1,'']]],
  ['storage_20keys_3a_20strong_12',['&lt;strong&gt;Storage Keys:&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md36',1,'']]],
  ['strong_201_20compile_20time_20constants_20tt_20configconstants_20tt_20namespace_13',['&lt;strong&gt;1. Compile-Time Constants (&lt;tt&gt;ConfigConstants&lt;/tt&gt; namespace)**',['../md_CONFIG__README.html#autotoc_md2',1,'']]],
  ['strong_201_20reading_20values_20strong_14',['&lt;strong&gt;1. Reading Values&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md25',1,'']]],
  ['strong_202_20changing_20runtime_20values_20temporary_20strong_15',['&lt;strong&gt;2. Changing Runtime Values (Temporary)&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md26',1,'']]],
  ['strong_202_20runtime_20configuration_20classes_20strong_16',['&lt;strong&gt;2. Runtime Configuration Classes&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md3',1,'']]],
  ['strong_203_20changing_20runtime_20values_20permanent_20strong_17',['&lt;strong&gt;3. Changing Runtime Values (Permanent)&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md27',1,'']]],
  ['strong_203_20main_20config_20class_20singleton_20strong_18',['&lt;strong&gt;3. Main Config Class (Singleton)&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md4',1,'']]],
  ['strong_204_20using_20in_20your_20code_20strong_19',['&lt;strong&gt;4. Using in Your Code&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md28',1,'']]],
  ['strong_20check_20current_20configuration_3a_20strong_20',['&lt;strong&gt;Check Current Configuration:&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md48',1,'']]],
  ['strong_20do_20s_3a_20strong_21',['&lt;strong&gt;Do&apos;s:&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md54',1,'']]],
  ['strong_20don_20ts_3a_20strong_22',['&lt;strong&gt;Don&apos;ts:&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md55',1,'']]],
  ['strong_20firmware_20constants_20strong_23',['&lt;strong&gt;Firmware Constants&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md11',1,'']]],
  ['strong_20firmwareconfig_20strong_20update_20management_24',['&lt;strong&gt;FirmwareConfig&lt;/strong&gt; - Update Management',['../md_CONFIG__README.html#autotoc_md17',1,'']]],
  ['strong_20getting_20the_20config_20instance_20strong_25',['&lt;strong&gt;Getting the Config Instance&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md21',1,'']]],
  ['strong_20hardware_20constants_20strong_26',['&lt;strong&gt;Hardware Constants&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md9',1,'']]],
  ['strong_20hardwareconfig_20strong_20device_20settings_27',['&lt;strong&gt;HardwareConfig&lt;/strong&gt; - Device Settings',['../md_CONFIG__README.html#autotoc_md16',1,'']]],
  ['strong_20initialization_20in_20setup_20strong_28',['&lt;strong&gt;Initialization (in setup())&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md22',1,'']]],
  ['strong_20network_20constants_20strong_29',['&lt;strong&gt;Network Constants&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md12',1,'']]],
  ['strong_20networkconfig_20strong_20device_20identity_30',['&lt;strong&gt;NetworkConfig&lt;/strong&gt; - Device Identity',['../md_CONFIG__README.html#autotoc_md18',1,'']]],
  ['strong_20reset_20to_20defaults_3a_20strong_31',['&lt;strong&gt;Reset to Defaults:&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md49',1,'']]],
  ['strong_20step_201_3a_20add_20constants_20if_20needed_20strong_32',['&lt;strong&gt;Step 1: Add Constants (if needed)&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md43',1,'']]],
  ['strong_20step_202_3a_20create_20runtime_20config_20class_20strong_33',['&lt;strong&gt;Step 2: Create Runtime Config Class&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md44',1,'']]],
  ['strong_20step_203_3a_20add_20to_20main_20config_20class_20strong_34',['&lt;strong&gt;Step 3: Add to Main Config Class&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md45',1,'']]],
  ['strong_20storage_20details_3a_20strong_35',['&lt;strong&gt;Storage Details:&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md35',1,'']]],
  ['strong_20storage_20keys_3a_20strong_36',['&lt;strong&gt;Storage Keys:&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md36',1,'']]],
  ['strong_20timing_20constants_20strong_37',['&lt;strong&gt;Timing Constants&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md10',1,'']]],
  ['strong_20what_20gets_20saved_20automatically_3a_20strong_38',['&lt;strong&gt;What Gets Saved Automatically:&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md34',1,'']]],
  ['strong_20wifi_20constants_20strong_39',['&lt;strong&gt;WiFi Constants&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md8',1,'']]],
  ['strong_20wificonfig_20strong_20network_20settings_40',['&lt;strong&gt;WiFiConfig&lt;/strong&gt; - Network Settings',['../md_CONFIG__README.html#autotoc_md15',1,'']]],
  ['structure_41',['File Structure',['../md_README.html#autotoc_md81',1,'']]],
  ['system_42',['📖 How to Use the Config System',['../md_CONFIG__README.html#autotoc_md24',1,'']]],
  ['system_20guide_43',['📋 ESP32 Configuration System Guide',['../md_CONFIG__README.html',1,'']]]
];
