var searchData=
[
  ['categories_3a_0',['Available Constant Categories:',['../md_CONFIG__README.html#autotoc_md7',1,'']]],
  ['changing_20runtime_20values_20permanent_20strong_1',['&lt;strong&gt;3. Changing Runtime Values (Permanent)&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md27',1,'']]],
  ['changing_20runtime_20values_20temporary_20strong_2',['&lt;strong&gt;2. Changing Runtime Values (Temporary)&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md26',1,'']]],
  ['check_20current_20configuration_3a_20strong_3',['&lt;strong&gt;Check Current Configuration:&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md48',1,'']]],
  ['class_20singleton_20strong_4',['&lt;strong&gt;3. Main Config Class (Singleton)&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md4',1,'']]],
  ['class_20strong_5',['class strong',['../md_CONFIG__README.html#autotoc_md44',1,'&lt;strong&gt;Step 2: Create Runtime Config Class&lt;/strong&gt;'],['../md_CONFIG__README.html#autotoc_md45',1,'&lt;strong&gt;Step 3: Add to Main Config Class&lt;/strong&gt;']]],
  ['class_20usage_6',['🎯 Layer 3: Main Config Class Usage',['../md_CONFIG__README.html#autotoc_md20',1,'']]],
  ['classes_7',['🔄 Layer 2: Runtime Configuration Classes',['../md_CONFIG__README.html#autotoc_md14',1,'']]],
  ['classes_20strong_8',['&lt;strong&gt;2. Runtime Configuration Classes&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md3',1,'']]],
  ['code_20strong_9',['&lt;strong&gt;4. Using in Your Code&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md28',1,'']]],
  ['compatibility_10',['🔍 Backward Compatibility',['../md_CONFIG__README.html#autotoc_md38',1,'']]],
  ['compile_20time_20constants_11',['🔧 Layer 1: Compile-Time Constants',['../md_CONFIG__README.html#autotoc_md6',1,'']]],
  ['compile_20time_20constants_20tt_20configconstants_20tt_20namespace_12',['&lt;strong&gt;1. Compile-Time Constants (&lt;tt&gt;ConfigConstants&lt;/tt&gt; namespace)**',['../md_CONFIG__README.html#autotoc_md2',1,'']]],
  ['complete_20implementation_13',['📝 Example: Complete Implementation',['../md_CONFIG__README.html#autotoc_md57',1,'']]],
  ['config_20class_20singleton_20strong_14',['&lt;strong&gt;3. Main Config Class (Singleton)&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md4',1,'']]],
  ['config_20class_20strong_15',['config class strong',['../md_CONFIG__README.html#autotoc_md44',1,'&lt;strong&gt;Step 2: Create Runtime Config Class&lt;/strong&gt;'],['../md_CONFIG__README.html#autotoc_md45',1,'&lt;strong&gt;Step 3: Add to Main Config Class&lt;/strong&gt;']]],
  ['config_20class_20usage_16',['🎯 Layer 3: Main Config Class Usage',['../md_CONFIG__README.html#autotoc_md20',1,'']]],
  ['config_20instance_20strong_17',['&lt;strong&gt;Getting the Config Instance&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md21',1,'']]],
  ['config_20system_18',['📖 How to Use the Config System',['../md_CONFIG__README.html#autotoc_md24',1,'']]],
  ['configconstants_20tt_20namespace_19',['&lt;strong&gt;1. Compile-Time Constants (&lt;tt&gt;ConfigConstants&lt;/tt&gt; namespace)**',['../md_CONFIG__README.html#autotoc_md2',1,'']]],
  ['configuration_20',['configuration',['../md_README.html#autotoc_md67',1,'Configuration'],['../md_README.html#autotoc_md63',1,'Pin Configuration']]],
  ['configuration_20classes_21',['🔄 Layer 2: Runtime Configuration Classes',['../md_CONFIG__README.html#autotoc_md14',1,'']]],
  ['configuration_20classes_20strong_22',['&lt;strong&gt;2. Runtime Configuration Classes&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md3',1,'']]],
  ['configuration_20options_23',['🛠️ Adding New Configuration Options',['../md_CONFIG__README.html#autotoc_md42',1,'']]],
  ['configuration_20status_20debugging_24',['📊 Configuration Status &amp; Debugging',['../md_CONFIG__README.html#autotoc_md47',1,'']]],
  ['configuration_20system_20guide_25',['📋 ESP32 Configuration System Guide',['../md_CONFIG__README.html',1,'']]],
  ['configuration_3a_20strong_26',['&lt;strong&gt;Check Current Configuration:&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md48',1,'']]],
  ['connection_20example_3a_27',['WiFi Connection Example:',['../md_CONFIG__README.html#autotoc_md29',1,'']]],
  ['constant_20categories_3a_28',['Available Constant Categories:',['../md_CONFIG__README.html#autotoc_md7',1,'']]],
  ['constants_29',['🔧 Layer 1: Compile-Time Constants',['../md_CONFIG__README.html#autotoc_md6',1,'']]],
  ['constants_20if_20needed_20strong_30',['&lt;strong&gt;Step 1: Add Constants (if needed)&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md43',1,'']]],
  ['constants_20strong_31',['constants strong',['../md_CONFIG__README.html#autotoc_md11',1,'&lt;strong&gt;Firmware Constants&lt;/strong&gt;'],['../md_CONFIG__README.html#autotoc_md9',1,'&lt;strong&gt;Hardware Constants&lt;/strong&gt;'],['../md_CONFIG__README.html#autotoc_md12',1,'&lt;strong&gt;Network Constants&lt;/strong&gt;'],['../md_CONFIG__README.html#autotoc_md10',1,'&lt;strong&gt;Timing Constants&lt;/strong&gt;'],['../md_CONFIG__README.html#autotoc_md8',1,'&lt;strong&gt;WiFi Constants&lt;/strong&gt;']]],
  ['constants_20tt_20configconstants_20tt_20namespace_32',['&lt;strong&gt;1. Compile-Time Constants (&lt;tt&gt;ConfigConstants&lt;/tt&gt; namespace)**',['../md_CONFIG__README.html#autotoc_md2',1,'']]],
  ['control_20example_3a_33',['LED Control Example:',['../md_CONFIG__README.html#autotoc_md30',1,'']]],
  ['core_20functionality_34',['Core Functionality',['../md_README.html#autotoc_md60',1,'']]],
  ['create_20runtime_20config_20class_20strong_35',['&lt;strong&gt;Step 2: Create Runtime Config Class&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md44',1,'']]],
  ['current_20configuration_3a_20strong_36',['&lt;strong&gt;Check Current Configuration:&lt;/strong&gt;',['../md_CONFIG__README.html#autotoc_md48',1,'']]],
  ['custom_20libraries_37',['Custom Libraries',['../md_README.html#autotoc_md66',1,'']]]
];
