name: Build and Release Firmware

on:
  workflow_dispatch:
    inputs:
      major_version:
        description: 'Major version number'
        required: true
        default: '9'
        type: string
      minor_version:
        description: 'Minor version number'
        required: true
        default: '1'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: pip install platformio

      - name: Update version in firmware.json and main.cpp
        run: python set_version.py ${{ github.event.inputs.major_version }} ${{ github.event.inputs.minor_version }}

      - name: Commit version update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/main.cpp firmware.json
          git commit -m "Update firmware version to v${{ github.event.inputs.major_version }}.${{ github.event.inputs.minor_version }}" || echo "No changes to commit"
          git push

      - name: Build firmware
        run: |
          platformio run --environment esp32doit-devkit-v1
          platformio run --environment seeed_xiao_esp32s3

      - name: Copy firmware to Release folder
        run: |
          mkdir -p Release
          # Copy and rename firmware files with board-specific names
          cp .pio/build/esp32doit-devkit-v1/firmware.bin Release/firmware-esp32-devkit.bin
          cp .pio/build/seeed_xiao_esp32s3/firmware.bin Release/firmware-xiao-esp32s3.bin
          # Also copy a generic firmware.bin (defaulting to devkit for backward compatibility)
          cp .pio/build/esp32doit-devkit-v1/firmware.bin Release/firmware.bin

      - name: Copy firmware.json to Release folder
        run: cp firmware.json Release/

      - name: Create GitHub Release and Upload Firmware
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.major_version }}.${{ github.event.inputs.minor_version }}
          name: Firmware v${{ github.event.inputs.major_version }}.${{ github.event.inputs.minor_version }}
          files: |
            Release/firmware.bin
            Release/firmware-esp32-devkit.bin
            Release/firmware-xiao-esp32s3.bin
            Release/firmware.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
