name: Manual Build Only

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install ESP-IDF and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install esptool
      - name: Build project
        run: |
          idf.py build
